#!/usr/bin/env nextflow

process BOWTIE2_BUILD {
    label 'process_high'
    conda 'envs/bowtie2_env.yml'

    // Publish bowtie2 index into refs folder
    publishDir "${params.refdir}/bowtie2_index", mode: 'copy'

    input:
    path genome

    output:
    // Emit all index files generated by bowtie2-build
    path "bowtie2_index", emit: index

    script:
    """
    mkdir -p bowtie2_index

    # Build Bowtie2 index
    bowtie2-build --threads ${task.cpus} ${genome} bowtie2_index/genome
    """
    
    stub:
    """
    mkdir -p bowtie2_index
    # Create placeholder index files for stub mode
    touch bowtie2_index/genome.1.bt2
    touch bowtie2_index/genome.2.bt2
    touch bowtie2_index/genome.3.bt2
    touch bowtie2_index/genome.4.bt2
    touch bowtie2_index/genome.rev.1.bt2
    touch bowtie2_index/genome.rev.2.bt2
    """
}
